[package]
name = "sober_cash"
version = "1.0.0"
authors = []

[addresses]
sober_cash = "_"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
